version: "3"

services:

  apiUser:
    image: "apiuser"
    ports:
      - 8088:8088
    environment:
      DB_URL: jdbc:postgresql://database:5432/postgres
    restart: always

  apiStock:
    image: "apistock"
    ports:
      - 8089:8089
    environment:
      DB_URL: jdbc:postgresql://database:5432/stocks
    restart: always

  database:
    image: "postgres"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: stocks
    volumes:
      - /var/usr/lib/postgresql/14/main

    restart: always
  front:
    image: "oktafront"
    ports:
      - 8080:8080

