
create table stocks(
                       id bigint primary key generated always as identity,
                       stock_symbol text not null,
                       stock_name text not null,
                       ask_min numeric,
                       ask_max numeric,
                       bid_min numeric,
                       bid_max numeric,
                       created_on timestamp not null default current_timestamp,
                       updated_on timestamp not null default current_timestamp
);


insert into stocks( stock_symbol, stock_name) values ('BEEF', 'MINERVA');
insert into stocks( stock_symbol, stock_name) values ('EMBR', 'EMBRAER');
insert into stocks( stock_symbol, stock_name) values ('DESK', 'DESKTOP');
insert into stocks( stock_symbol, stock_name) values ('MOSI', 'MOSAICO');
insert into stocks( stock_symbol, stock_name) values ('ETER', 'ETERNIT');
insert into stocks( stock_symbol, stock_name) values ('MEAL', 'IMC S/A');
insert into stocks( stock_symbol, stock_name) values ('DOTZ', 'DOTZ SA');
insert into stocks( stock_symbol, stock_name) values ('BRKM', 'BRASKEM');
insert into stocks( stock_symbol, stock_name) values ('UCAS', 'UNICASA');
insert into stocks( stock_symbol, stock_name) values ('HASH', 'HASHDEX');
insert into stocks( stock_symbol, stock_name) values ('FRAS', 'FRAS-LE');
insert into stocks( stock_symbol, stock_name) values ('MELK', 'MELNICK');
insert into stocks( stock_symbol, stock_name) values ('ATTB', 'ATT INC');
insert into stocks( stock_symbol, stock_name) values ('COTY', 'COTY INC');
insert into stocks( stock_symbol, stock_name) values ('CHVX', 'CHEVRON');
insert into stocks( stock_symbol, stock_name) values ('IBCR', 'FII BREI');
insert into stocks( stock_symbol, stock_name) values ('BBYY', 'BEST BUY');
insert into stocks( stock_symbol, stock_name) values ('ARMT', 'ARCELOR');
insert into stocks( stock_symbol, stock_name) values ('BRIT', 'BRISANET');
insert into stocks( stock_symbol, stock_name) values ('CRIP', 'CTRIPCOM');
insert into stocks( stock_symbol, stock_name) values ('LMTB', 'LOCKHEED');
insert into stocks( stock_symbol, stock_name) values ('BKNG', 'BOOKING');
insert into stocks( stock_symbol, stock_name) values ('CMCS', 'COMCAST');
insert into stocks( stock_symbol, stock_name) values ('GURU', 'ETF GURU');
insert into stocks( stock_symbol, stock_name) values ('BCIA', 'FII BCIA');
insert into stocks( stock_symbol, stock_name) values ('COLG', 'COLGATE');
insert into stocks( stock_symbol, stock_name) values ('MCCI', 'FII MAUA');
insert into stocks( stock_symbol, stock_name) values ('BTLG', 'FII BTLG');
insert into stocks( stock_symbol, stock_name) values ('FOXC', 'FOX CORP');
insert into stocks( stock_symbol, stock_name) values ('GRND', 'GRENDENE');
insert into stocks( stock_symbol, stock_name) values ('LUPA', 'LUPATECH');
insert into stocks( stock_symbol, stock_name) values ('DEEC', 'DEERE CO');
insert into stocks( stock_symbol, stock_name) values ('FCXO', 'FREEPORT');
insert into stocks( stock_symbol, stock_name) values ('BRSR', 'BANRISUL');
insert into stocks( stock_symbol, stock_name) values ('NETE', 'NETEASE');
insert into stocks( stock_symbol, stock_name) values ('NFLX', 'NETFLIX');
insert into stocks( stock_symbol, stock_name) values ('RCSL', 'RECRUSUL');
insert into stocks( stock_symbol, stock_name) values ('RENT', 'LOCALIZA');
insert into stocks( stock_symbol, stock_name) values ('TMCO', 'TOYOTAMO');
insert into stocks( stock_symbol, stock_name) values ('ULEV', 'UNILEVER');
insert into stocks( stock_symbol, stock_name) values ('USSX', 'US STEEL');
insert into stocks( stock_symbol, stock_name) values ('VISA', 'VISA INC');
insert into stocks( stock_symbol, stock_name) values ('USIM', 'USIMINAS');
insert into stocks( stock_symbol, stock_name) values ('IRIM', 'FII IRIM');
insert into stocks( stock_symbol, stock_name) values ('CRHP', 'CRH PLC');
insert into stocks( stock_symbol, stock_name) values ('JNJB', 'JOHNSON');
insert into stocks( stock_symbol, stock_name) values ('QCOM', 'QUALCOMM');
insert into stocks( stock_symbol, stock_name) values ('VERZ', 'VERIZON');
insert into stocks( stock_symbol, stock_name) values ('CSXC', 'CSX CORP');
insert into stocks( stock_symbol, stock_name) values ('CSED', 'CRUZEIRO');
insert into stocks( stock_symbol, stock_name) values ('FIQE', 'UNIFIQUE');
insert into stocks( stock_symbol, stock_name) values ('PRIO', 'PETRORIO');
insert into stocks( stock_symbol, stock_name) values ('TWTR', 'TWITTER');
insert into stocks( stock_symbol, stock_name) values ('GOGL', 'ALPHABET');
insert into stocks( stock_symbol, stock_name) values ('HAGA', 'HAGA S/A');
insert into stocks( stock_symbol, stock_name) values ('FASL', 'FASTENAL');
insert into stocks( stock_symbol, stock_name) values ('WEST', 'WESTWING');
insert into stocks( stock_symbol, stock_name) values ('ENGI', 'ENERGISA');
insert into stocks( stock_symbol, stock_name) values ('ZIFI', 'FII ZION');
insert into stocks( stock_symbol, stock_name) values ('CURY', 'CURY S/A');
insert into stocks( stock_symbol, stock_name) values ('PFRM', 'PROFARMA');
insert into stocks( stock_symbol, stock_name) values ('QETH', 'QR ETHER');
insert into stocks( stock_symbol, stock_name) values ('TELB', 'TELEBRAS');
insert into stocks( stock_symbol, stock_name) values ('HOND', 'HONDA MO');
insert into stocks( stock_symbol, stock_name) values ('BEWU', 'MSCI UK');
insert into stocks( stock_symbol, stock_name) values ('ABUD', 'AB INBEV');
insert into stocks( stock_symbol, stock_name) values ('JPMC', 'JPMORGAN');
insert into stocks( stock_symbol, stock_name) values ('PSVM', 'PORTO VM');
insert into stocks( stock_symbol, stock_name) values ('TAKP', 'TAKEDAPH');
insert into stocks( stock_symbol, stock_name) values ('UGPA', 'ULTRAPAR');
insert into stocks( stock_symbol, stock_name) values ('BBDC', 'BRADESCO');
insert into stocks( stock_symbol, stock_name) values ('RBED', 'FII RIOB');
insert into stocks( stock_symbol, stock_name) values ('RDSA', 'RD SHELL');
insert into stocks( stock_symbol, stock_name) values ('WALM', 'WAL MART');
insert into stocks( stock_symbol, stock_name) values ('WIZS', 'WIZ S.A.');
insert into stocks( stock_symbol, stock_name) values ('HETA', 'HERCULES');
insert into stocks( stock_symbol, stock_name) values ('BEES', 'BANESTES');
insert into stocks( stock_symbol, stock_name) values ('LIPR', 'ELETROPAR');
insert into stocks( stock_symbol, stock_name) values ('BOAS', 'BOA VISTA');
insert into stocks( stock_symbol, stock_name) values ('EQPA', 'EQTL PARA');
insert into stocks( stock_symbol, stock_name) values ('LUGG', 'FII LUGGO');
insert into stocks( stock_symbol, stock_name) values ('HOSI', 'FII HOUSI');
insert into stocks( stock_symbol, stock_name) values ('KNRI', 'FII KINEA');
insert into stocks( stock_symbol, stock_name) values ('IFIE', 'FII IFI-E');
insert into stocks( stock_symbol, stock_name) values ('LIGT', 'LIGHT S/A');
insert into stocks( stock_symbol, stock_name) values ('JHSF', 'JHSF PART');
insert into stocks( stock_symbol, stock_name) values ('BIDB', 'FIC INTER');
insert into stocks( stock_symbol, stock_name) values ('BKBR', 'BK BRASIL');
insert into stocks( stock_symbol, stock_name) values ('CTNM', 'COTEMINAS');
insert into stocks( stock_symbol, stock_name) values ('CLSA', 'CLEARSALE');
insert into stocks( stock_symbol, stock_name) values ('BPAN', 'BANCO PAN');
insert into stocks( stock_symbol, stock_name) values ('RAIL', 'RUMO S.A.');
insert into stocks( stock_symbol, stock_name) values ('TCNO', 'TECNOSOLO');
insert into stocks( stock_symbol, stock_name) values ('OPCT', 'OCEANPACT');
insert into stocks( stock_symbol, stock_name) values ('PDGR', 'PDG REALT');
insert into stocks( stock_symbol, stock_name) values ('PTNT', 'PETTENATI');
insert into stocks( stock_symbol, stock_name) values ('VULC', 'VULCABRAS');
insert into stocks( stock_symbol, stock_name) values ('ARZZ', 'AREZZO CO');
insert into stocks( stock_symbol, stock_name) values ('IFID', 'FII IFI-D');
insert into stocks( stock_symbol, stock_name) values ('RBRD', 'FII RB II');
insert into stocks( stock_symbol, stock_name) values ('ROMI', 'INDS ROMI');
insert into stocks( stock_symbol, stock_name) values ('TRNT', 'FII TORRE');
insert into stocks( stock_symbol, stock_name) values ('BAUH', 'EXCELSIOR');
insert into stocks( stock_symbol, stock_name) values ('MODL', 'MODALMAIS');
insert into stocks( stock_symbol, stock_name) values ('BSLI', 'BRB BANCO');
insert into stocks( stock_symbol, stock_name) values ('GETT', 'GETNET BR');
insert into stocks( stock_symbol, stock_name) values ('BMGB', 'BANCO BMG');
insert into stocks( stock_symbol, stock_name) values ('PARD', 'IHPARDINI');
insert into stocks( stock_symbol, stock_name) values ('QUAL', 'QUALICORP');
insert into stocks( stock_symbol, stock_name) values ('RDOR', 'REDE D OR');
insert into stocks( stock_symbol, stock_name) values ('MULT', 'MULTIPLAN');
insert into stocks( stock_symbol, stock_name) values ('SBFG', 'GRUPO SBF');
insert into stocks( stock_symbol, stock_name) values ('INTB', 'INTELBRAS');
insert into stocks( stock_symbol, stock_name) values ('ARRI', 'FII ATRIO');
insert into stocks( stock_symbol, stock_name) values ('WHRL', 'WHIRLPOOL');
insert into stocks( stock_symbol, stock_name) values ('GPIV', 'GP INVEST');
insert into stocks( stock_symbol, stock_name) values ('IVVB', 'ISHARE SP');
insert into stocks( stock_symbol, stock_name) values ('NUBR', 'NU-NUBANK');
insert into stocks( stock_symbol, stock_name) values ('STOC', 'STONE CO');
insert into stocks( stock_symbol, stock_name) values ('XPBR', 'XP INC  ');
insert into stocks( stock_symbol, stock_name) values ('IFCM', 'INFRACOMM');
insert into stocks( stock_symbol, stock_name) values ('CEAB', 'CEA MODAS');
insert into stocks( stock_symbol, stock_name) values ('HBSA', 'HIDROVIAS');
insert into stocks( stock_symbol, stock_name) values ('NINJ', 'GETNINJAS');
insert into stocks( stock_symbol, stock_name) values ('POMO', 'MARCOPOLO');
insert into stocks( stock_symbol, stock_name) values ('PETR', 'PETROBRAS');
insert into stocks( stock_symbol, stock_name) values ('BRAP', 'BRADESPAR');
insert into stocks( stock_symbol, stock_name) values ('MATD', 'MATER DEI');
insert into stocks( stock_symbol, stock_name) values ('MGFF', 'FII MOGNO');
insert into stocks( stock_symbol, stock_name) values ('SMFT', 'SMART FIT');
insert into stocks( stock_symbol, stock_name) values ('SOJA', 'BOA SAFRA');
insert into stocks( stock_symbol, stock_name) values ('BICR', 'FII INTER');
insert into stocks( stock_symbol, stock_name) values ('ABEV', 'AMBEV S/A');
insert into stocks( stock_symbol, stock_name) values ('FSTU', 'FISET TUR');
insert into stocks( stock_symbol, stock_name) values ('BACW', 'MSCI ACWIN');
insert into stocks( stock_symbol, stock_name) values ('DEOP', 'DIAGEO PLN');
insert into stocks( stock_symbol, stock_name) values ('BIDU', 'BAIDU INCN');
insert into stocks( stock_symbol, stock_name) values ('BEFA', 'MSCI');
insert into stocks( stock_symbol, stock_name) values ('MCDC', 'MCDONALDSN');
insert into stocks( stock_symbol, stock_name) values ('BERK', 'BERKSHIREN');
insert into stocks( stock_symbol, stock_name) values ('ASML', 'ASML HOLDN');
insert into stocks( stock_symbol, stock_name) values ('MOSC', 'MOSAIC CON');
insert into stocks( stock_symbol, stock_name) values ('BCSA', 'SANTANDERN');
insert into stocks( stock_symbol, stock_name) values ('RIOT', 'RIO TINTON');
insert into stocks( stock_symbol, stock_name) values ('ACNB', 'ACCENTUREN');
insert into stocks( stock_symbol, stock_name) values ('HONB', 'HONEYWELLN');
insert into stocks( stock_symbol, stock_name) values ('MSFT', 'MICROSOFTN');
insert into stocks( stock_symbol, stock_name) values ('PAGS', 'PAGSEGURON');
insert into stocks( stock_symbol, stock_name) values ('PTCH', 'PETROCHINN');
insert into stocks( stock_symbol, stock_name) values ('MDTC', 'MEDTRONICN');
insert into stocks( stock_symbol, stock_name) values ('BILB', 'BILBAOVIZN');
insert into stocks( stock_symbol, stock_name) values ('BHPG', 'BHP GROUPN');
insert into stocks( stock_symbol, stock_name) values ('TSLA', 'TESLA INCN');
insert into stocks( stock_symbol, stock_name) values ('ADBE', 'ADOBE INCN');
insert into stocks( stock_symbol, stock_name) values ('SPGI', 'SP GLOBALN');
insert into stocks( stock_symbol, stock_name) values ('TLNC', 'TELEFONICN');
insert into stocks( stock_symbol, stock_name) values ('UBSG', 'UBS GROUPN');
insert into stocks( stock_symbol, stock_name) values ('BLAK', 'BLACKROCKN');
insert into stocks( stock_symbol, stock_name) values ('WGBA', 'WALGREENSN');
insert into stocks( stock_symbol, stock_name) values ('COCA', 'COCA COLAN');
insert into stocks( stock_symbol, stock_name) values ('BILF', 'LATIN AMER');
insert into stocks( stock_symbol, stock_name) values ('NMRH', 'NOMURA HON');
insert into stocks( stock_symbol, stock_name) values ('STMN', 'STMICROELN');
insert into stocks( stock_symbol, stock_name) values ('TEXA', 'TEXAS INCN');
insert into stocks( stock_symbol, stock_name) values ('CTSH', 'COGNIZANTN');
insert into stocks( stock_symbol, stock_name) values ('BABA', 'ALIBABAGRN');
insert into stocks( stock_symbol, stock_name) values ('SBUB', 'STARBUCKSN');
insert into stocks( stock_symbol, stock_name) values ('TXSA', 'TERNIUMSAN');
insert into stocks( stock_symbol, stock_name) values ('CTGP', 'CITIGROUPN');
insert into stocks( stock_symbol, stock_name) values ('FBOK', 'META PLATN');
insert into stocks( stock_symbol, stock_name) values ('HGIC', 'FII HGI CRI');
insert into stocks( stock_symbol, stock_name) values ('BEWW', 'MSCI MEXICO');
insert into stocks( stock_symbol, stock_name) values ('EURO', 'FII EUROPAR');
insert into stocks( stock_symbol, stock_name) values ('GUAR', 'GUARARAPES');
insert into stocks( stock_symbol, stock_name) values ('BLCP', 'FII BLUECAP');
insert into stocks( stock_symbol, stock_name) values ('DISB', 'WALT DISNEY');
insert into stocks( stock_symbol, stock_name) values ('GSFI', 'FII GENERAL');
insert into stocks( stock_symbol, stock_name) values ('GNDI', 'INTERMEDICA');
insert into stocks( stock_symbol, stock_name) values ('HOME', 'HOME DEPOT');
insert into stocks( stock_symbol, stock_name) values ('GTLG', 'FII GTIS LG');
insert into stocks( stock_symbol, stock_name) values ('BMKS', 'BIC MONARK');
insert into stocks( stock_symbol, stock_name) values ('ENBR', 'ENERGIAS BR');
insert into stocks( stock_symbol, stock_name) values ('BIBB', 'ICE BIOTECH');
insert into stocks( stock_symbol, stock_name) values ('BRCR', 'FII BC FUND');
insert into stocks( stock_symbol, stock_name) values ('AMER', 'AMERICANAS');
insert into stocks( stock_symbol, stock_name) values ('APER', 'ALPER S.A.');
insert into stocks( stock_symbol, stock_name) values ('ARCT', 'FII ARCTIUM');
insert into stocks( stock_symbol, stock_name) values ('BIXN', 'GLOBAL TECH');
insert into stocks( stock_symbol, stock_name) values ('AFLT', 'AFLUENTE T');
insert into stocks( stock_symbol, stock_name) values ('BEWZ', 'MSCI BRAZIL');
insert into stocks( stock_symbol, stock_name) values ('BIEV', 'EUROPE ETF');
insert into stocks( stock_symbol, stock_name) values ('BRCO', 'FII BRESCO');
insert into stocks( stock_symbol, stock_name) values ('BTCR', 'FII BTG CRI');
insert into stocks( stock_symbol, stock_name) values ('FRTA', 'POMIFRUTAS');
insert into stocks( stock_symbol, stock_name) values ('HRDF', 'FII HREALTY');
insert into stocks( stock_symbol, stock_name) values ('MAXR', 'FII MAX RET');
insert into stocks( stock_symbol, stock_name) values ('MCHY', 'FII MAUA HY');
insert into stocks( stock_symbol, stock_name) values ('ACWI', 'TREND ACWI');
insert into stocks( stock_symbol, stock_name) values ('CYCR', 'FII CYRELA');
insert into stocks( stock_symbol, stock_name) values ('ETHE', 'ETHER HASH');
insert into stocks( stock_symbol, stock_name) values ('BNBR', 'NORD BRASIL');
insert into stocks( stock_symbol, stock_name) values ('AGXY', 'AGROGALAXY');
insert into stocks( stock_symbol, stock_name) values ('AESB', 'AES BRASIL');
insert into stocks( stock_symbol, stock_name) values ('BLUT', 'B TECH EQI');
insert into stocks( stock_symbol, stock_name) values ('DLTR', 'DOLLAR TREE');
insert into stocks( stock_symbol, stock_name) values ('COPH', 'COPHILLIPS');
insert into stocks( stock_symbol, stock_name) values ('CTSA', 'SANTANENSE');
insert into stocks( stock_symbol, stock_name) values ('CXTL', 'FII CX TRX');
insert into stocks( stock_symbol, stock_name) values ('EQIX', 'EQUINIX INC');
insert into stocks( stock_symbol, stock_name) values ('FLRP', 'FII FLORIPA');
insert into stocks( stock_symbol, stock_name) values ('CNES', 'FII CENESP');
insert into stocks( stock_symbol, stock_name) values ('BBFO', 'FII BB FOF');
insert into stocks( stock_symbol, stock_name) values ('ESPA', 'ESPACOLASER');
insert into stocks( stock_symbol, stock_name) values ('HALI', 'HALLIBURTON');
insert into stocks( stock_symbol, stock_name) values ('METB', 'METLIFE INC');
insert into stocks( stock_symbol, stock_name) values ('EALT', 'ACO ALTONA');
insert into stocks( stock_symbol, stock_name) values ('MLAS', 'MULTILASER');
insert into stocks( stock_symbol, stock_name) values ('ASIA', 'TREND ASIA');
insert into stocks( stock_symbol, stock_name) values ('HSAF', 'FII HSI CRI');
insert into stocks( stock_symbol, stock_name) values ('KRSA', 'KORA SAUDE');
insert into stocks( stock_symbol, stock_name) values ('BBRC', 'FII BB CORP');
insert into stocks( stock_symbol, stock_name) values ('BEWT', 'MSCI TAIWAN');
insert into stocks( stock_symbol, stock_name) values ('BIAU', 'GOLD TRUST');
insert into stocks( stock_symbol, stock_name) values ('GPRK', 'GEOPARK LTD');
insert into stocks( stock_symbol, stock_name) values ('HGBS', 'FII HEDGEBS');
insert into stocks( stock_symbol, stock_name) values ('LVBI', 'FII VBI LOG');
insert into stocks( stock_symbol, stock_name) values ('MCHF', 'FII MAUA HF');
insert into stocks( stock_symbol, stock_name) values ('EPAR', 'EMBPAR S/A');
insert into stocks( stock_symbol, stock_name) values ('ESGB', 'ETF ESG BTG');
insert into stocks( stock_symbol, stock_name) values ('AGRO', 'BRASILAGRO');
insert into stocks( stock_symbol, stock_name) values ('BCFF', 'FII BC FFII');
insert into stocks( stock_symbol, stock_name) values ('BIJH', 'CORE MIDCAP');
insert into stocks( stock_symbol, stock_name) values ('BRPR', 'BR PROPERT');
insert into stocks( stock_symbol, stock_name) values ('EQTL', 'EQUATORIAL');
insert into stocks( stock_symbol, stock_name) values ('KEVE', 'FII EVEN II');
insert into stocks( stock_symbol, stock_name) values ('KHCB', 'KRAFT HEINZ');
insert into stocks( stock_symbol, stock_name) values ('LJQQ', 'QUERO-QUERO');
insert into stocks( stock_symbol, stock_name) values ('HPQB', 'HP COMPANY');
insert into stocks( stock_symbol, stock_name) values ('EXXO', 'EXXON MOBIL');
insert into stocks( stock_symbol, stock_name) values ('BEWJ', 'MSCI JAPAN');
insert into stocks( stock_symbol, stock_name) values ('KISU', 'FII KILIMA');
insert into stocks( stock_symbol, stock_name) values ('FDMO', 'FORD MOTORS');
insert into stocks( stock_symbol, stock_name) values ('CRIV', 'ALFA FINANC');
insert into stocks( stock_symbol, stock_name) values ('FSLR', 'FIRST SOLAR');
insert into stocks( stock_symbol, stock_name) values ('CVCB', 'CVC BRASIL');
insert into stocks( stock_symbol, stock_name) values ('CAPH', 'CAPRI HOLDI');
insert into stocks( stock_symbol, stock_name) values ('RBFF', 'FII RIOB FF');
insert into stocks( stock_symbol, stock_name) values ('FIIB', 'FII INDL BR');
insert into stocks( stock_symbol, stock_name) values ('IRDM', 'FII IRIDIUM');
insert into stocks( stock_symbol, stock_name) values ('HGRE', 'FII HG REAL');
insert into stocks( stock_symbol, stock_name) values ('NSLU', 'FII LOURDES');
insert into stocks( stock_symbol, stock_name) values ('PYPL', 'PAYPAL HOLD');
insert into stocks( stock_symbol, stock_name) values ('RBRL', 'FII RBR LOG');
insert into stocks( stock_symbol, stock_name) values ('RCFA', 'FII GP RCFA');
insert into stocks( stock_symbol, stock_name) values ('RECV', 'PETRORECSA');
insert into stocks( stock_symbol, stock_name) values ('RZAG', 'FIAGRO RIZA');
insert into stocks( stock_symbol, stock_name) values ('XMAL', 'TREND SMALL');
insert into stocks( stock_symbol, stock_name) values ('XPLG', 'FII XP LOG');
insert into stocks( stock_symbol, stock_name) values ('XPPR', 'FII XP PROP');
insert into stocks( stock_symbol, stock_name) values ('MOAR', 'MONT ARANHA');
insert into stocks( stock_symbol, stock_name) values ('BURT', 'BKR MS WLD');
insert into stocks( stock_symbol, stock_name) values ('DBAG', 'DEUTSCHE AK');
insert into stocks( stock_symbol, stock_name) values ('MORE', 'FII MORE RE');
insert into stocks( stock_symbol, stock_name) values ('CEOC', 'FII CEO CCP');
insert into stocks( stock_symbol, stock_name) values ('JSRE', 'FII JS REAL');
insert into stocks( stock_symbol, stock_name) values ('CVSH', 'CVS HEALTH');
insert into stocks( stock_symbol, stock_name) values ('DEVA', 'FII DEVANT');
insert into stocks( stock_symbol, stock_name) values ('MSBR', 'MORGAN STAN');
insert into stocks( stock_symbol, stock_name) values ('MSCD', 'MASTERCARD');
insert into stocks( stock_symbol, stock_name) values ('NEOE', 'NEOENERGIA');
insert into stocks( stock_symbol, stock_name) values ('NVDC', 'NVIDIA CORP');
insert into stocks( stock_symbol, stock_name) values ('ODPV', 'ODONTOPREV');
insert into stocks( stock_symbol, stock_name) values ('PABY', 'FII PANAMBY');
insert into stocks( stock_symbol, stock_name) values ('PATC', 'FII PATRIA');
insert into stocks( stock_symbol, stock_name) values ('PNCS', 'PNCFNANCIAL');
insert into stocks( stock_symbol, stock_name) values ('PPEI', 'FIP PRISMA');
insert into stocks( stock_symbol, stock_name) values ('RFOF', 'FII RB CFOF');
insert into stocks( stock_symbol, stock_name) values ('RIGG', 'TRANSOCEAN');
insert into stocks( stock_symbol, stock_name) values ('SDIL', 'FII SDI LOG');
insert into stocks( stock_symbol, stock_name) values ('SOMA', 'GRUPO SOMA');
insert into stocks( stock_symbol, stock_name) values ('SSFO', 'SALESFORCE');
insert into stocks( stock_symbol, stock_name) values ('STBP', 'SANTOS BRP');
insert into stocks( stock_symbol, stock_name) values ('TSMC', 'TAIWANSMFAC');
insert into stocks( stock_symbol, stock_name) values ('VGIA', 'FIAGRO VGIA');
insert into stocks( stock_symbol, stock_name) values ('XPCI', 'FII XP CRED');
insert into stocks( stock_symbol, stock_name) values ('XPHT', 'FII XP HOT');
insert into stocks( stock_symbol, stock_name) values ('XPIN', 'FII XP INDL');
insert into stocks( stock_symbol, stock_name) values ('BEMV', 'MSCIEMMRKMI');
insert into stocks( stock_symbol, stock_name) values ('BOVX', 'TREND IBOVX');
insert into stocks( stock_symbol, stock_name) values ('BREV', 'FII BRE VIC');
insert into stocks( stock_symbol, stock_name) values ('KMBB', 'KIMBERLY CL');
insert into stocks( stock_symbol, stock_name) values ('BRZP', 'FIP BRZ IE');
insert into stocks( stock_symbol, stock_name) values ('LASC', 'FII LEGATUS');
insert into stocks( stock_symbol, stock_name) values ('HSLG', 'FII HSI LOG');
insert into stocks( stock_symbol, stock_name) values ('LEVE', 'METAL LEVE');
insert into stocks( stock_symbol, stock_name) values ('MGLU', 'MAGAZ LUIZA');
insert into stocks( stock_symbol, stock_name) values ('BOXP', 'BOSTON PROP');
insert into stocks( stock_symbol, stock_name) values ('GOLD', 'TREND OURO');
insert into stocks( stock_symbol, stock_name) values ('BEWC', 'MSCI CANADA');
insert into stocks( stock_symbol, stock_name) values ('BIDI', 'BANCO INTER');
insert into stocks( stock_symbol, stock_name) values ('BIYE', 'BKR US ENER');
insert into stocks( stock_symbol, stock_name) values ('RECX', 'FII REC FOF');
insert into stocks( stock_symbol, stock_name) values ('SIMN', 'SIMON PROP');
insert into stocks( stock_symbol, stock_name) values ('BONY', 'BNY MELLON');
insert into stocks( stock_symbol, stock_name) values ('ECOR', 'ECORODOVIAS');
insert into stocks( stock_symbol, stock_name) values ('LOWC', 'LOWES COMPA');
insert into stocks( stock_symbol, stock_name) values ('QBTC', 'QR BITCOIN');
insert into stocks( stock_symbol, stock_name) values ('RELG', 'FII REC LOG');
insert into stocks( stock_symbol, stock_name) values ('SUZB', 'SUZANO S.A.');
insert into stocks( stock_symbol, stock_name) values ('TSER', 'FII TISHMAN');
insert into stocks( stock_symbol, stock_name) values ('XINA', 'TREND CHINA');
insert into stocks( stock_symbol, stock_name) values ('CATP', 'CATERPILLAR');
insert into stocks( stock_symbol, stock_name) values ('LCAM', 'LOCAMERICA');
insert into stocks( stock_symbol, stock_name) values ('SEQR', 'FII SEQUOIA');
insert into stocks( stock_symbol, stock_name) values ('VLOE', 'VALERO ENER');
insert into stocks( stock_symbol, stock_name) values ('BBRK', 'BR BROKERS');
insert into stocks( stock_symbol, stock_name) values ('BMOB', 'BEMOBI TECH');
insert into stocks( stock_symbol, stock_name) values ('HCTR', 'FII HECTARE');
insert into stocks( stock_symbol, stock_name) values ('BARI', 'FII BARIGUI');
insert into stocks( stock_symbol, stock_name) values ('ESGE', 'TREND ESG E');
insert into stocks( stock_symbol, stock_name) values ('KNOX', 'FIP IE KNOX');
insert into stocks( stock_symbol, stock_name) values ('ALPA', 'ALPARGATAS');
insert into stocks( stock_symbol, stock_name) values ('ATVI', 'ACTIVISION');
insert into stocks( stock_symbol, stock_name) values ('KLBN', 'KLABIN S/A');
insert into stocks( stock_symbol, stock_name) values ('SULA', 'SUL AMERICA');
insert into stocks( stock_symbol, stock_name) values ('ROST', 'ROSS STORES');
insert into stocks( stock_symbol, stock_name) values ('TGTB', 'TARGET CORP');
insert into stocks( stock_symbol, stock_name) values ('WFCO', 'WELLS FARGO');
insert into stocks( stock_symbol, stock_name) values ('GMCO', 'GENERAL MOT');
insert into stocks( stock_symbol, stock_name) values ('MBRF', 'FII MERC BR');
insert into stocks( stock_symbol, stock_name) values ('RCRB', 'FII RIOB RC');
insert into stocks( stock_symbol, stock_name) values ('BCHI', 'MSCI CHINA');
insert into stocks( stock_symbol, stock_name) values ('BNDA', 'MSCI INDIA');
insert into stocks( stock_symbol, stock_name) values ('DIRR', 'DIRECIONAL');
insert into stocks( stock_symbol, stock_name) values ('PGMN', 'PAGUE MENOS');
insert into stocks( stock_symbol, stock_name) values ('PORT', 'WILSON SONS');
insert into stocks( stock_symbol, stock_name) values ('RSID', 'ROSSI RESID');
insert into stocks( stock_symbol, stock_name) values ('SCAR', 'SAO CARLOS');
insert into stocks( stock_symbol, stock_name) values ('VTLT', 'FII VOT LOG');
insert into stocks( stock_symbol, stock_name) values ('WPLZ', 'FII W PLAZA');
insert into stocks( stock_symbol, stock_name) values ('BPAC', 'BTGP BANCO');
insert into stocks( stock_symbol, stock_name) values ('BBOV', 'BB ETF IBOV');
insert into stocks( stock_symbol, stock_name) values ('BEWQ', 'MSCI FRANCE');
insert into stocks( stock_symbol, stock_name) values ('CGRA', 'GRAZZIOTIN');
insert into stocks( stock_symbol, stock_name) values ('EGYR', 'FII ENERGY');
insert into stocks( stock_symbol, stock_name) values ('ALZR', 'FII ALIANZA');
insert into stocks( stock_symbol, stock_name) values ('ELMD', 'ELETROMIDIA');
insert into stocks( stock_symbol, stock_name) values ('JFLL', 'FII JFL LIV');
insert into stocks( stock_symbol, stock_name) values ('ESGD', 'TREND ESG D');
insert into stocks( stock_symbol, stock_name) values ('ELET', 'ELETROBRAS');
insert into stocks( stock_symbol, stock_name) values ('ENAT', 'ENAUTA PART');
insert into stocks( stock_symbol, stock_name) values ('BERU', 'BKR MS RUSS');
insert into stocks( stock_symbol, stock_name) values ('EDGA', 'FII GALERIA');
insert into stocks( stock_symbol, stock_name) values ('DUKB', 'DUKE ENERGY');
insert into stocks( stock_symbol, stock_name) values ('ATSA', 'FII HATRIUM');
insert into stocks( stock_symbol, stock_name) values ('FDXB', 'FEDEX CORP');
insert into stocks( stock_symbol, stock_name) values ('BGRT', 'GLOBAL REIT');
insert into stocks( stock_symbol, stock_name) values ('CRFF', 'FII CX RBRA');
insert into stocks( stock_symbol, stock_name) values ('HFOF', 'FII HTOPFOF');
insert into stocks( stock_symbol, stock_name) values ('RBDS', 'FII RBRESID');
insert into stocks( stock_symbol, stock_name) values ('RBVO', 'FII RIOBCRI');
insert into stocks( stock_symbol, stock_name) values ('INTU', 'INTUIT INC');
insert into stocks( stock_symbol, stock_name) values ('OULG', 'FII OURILOG');
insert into stocks( stock_symbol, stock_name) values ('PEPB', 'PEPSICO INC');
insert into stocks( stock_symbol, stock_name) values ('PFIN', 'FIP PERFIN');
insert into stocks( stock_symbol, stock_name) values ('PQDP', 'FII D PEDRO');
insert into stocks( stock_symbol, stock_name) values ('RBRS', 'FII RIOB RR');
insert into stocks( stock_symbol, stock_name) values ('RZTR', 'FII RIZA TX');
insert into stocks( stock_symbol, stock_name) values ('SNEC', 'SONY GROUP');
insert into stocks( stock_symbol, stock_name) values ('USBC', 'US BANCORP');
insert into stocks( stock_symbol, stock_name) values ('VIVA', 'VIVARA S.A.');
insert into stocks( stock_symbol, stock_name) values ('VLOL', 'FII OLIMPIA');
insert into stocks( stock_symbol, stock_name) values ('YDUQ', 'YDUQS PART');
insert into stocks( stock_symbol, stock_name) values ('CVBI', 'FII VBI CRI');
insert into stocks( stock_symbol, stock_name) values ('EVBI', 'FII VBI CON');
insert into stocks( stock_symbol, stock_name) values ('HSHY', 'HERSHEY CO');
insert into stocks( stock_symbol, stock_name) values ('DEXP', 'DEXXOS PAR');
insert into stocks( stock_symbol, stock_name) values ('JGPX', 'FIAGRO JGP');
insert into stocks( stock_symbol, stock_name) values ('BIME', 'FII BRIO ME');
insert into stocks( stock_symbol, stock_name) values ('EMEG', 'TREND EMEG');
insert into stocks( stock_symbol, stock_name) values ('NOKI', 'NOKIA CORP');
insert into stocks( stock_symbol, stock_name) values ('ORLY', 'OREILLY AUT');
insert into stocks( stock_symbol, stock_name) values ('OSXB', 'OSX BRASIL');
insert into stocks( stock_symbol, stock_name) values ('PLRI', 'FII POLO I');
insert into stocks( stock_symbol, stock_name) values ('PTBL', 'PORTOBELLO');
insert into stocks( stock_symbol, stock_name) values ('PVBI', 'FII VBI PRI');
insert into stocks( stock_symbol, stock_name) values ('RBVA', 'FII RIOB VA');
insert into stocks( stock_symbol, stock_name) values ('SEQL', 'SEQUOIA LOG');
insert into stocks( stock_symbol, stock_name) values ('TECB', 'TECH BRASIL');
insert into stocks( stock_symbol, stock_name) values ('TSNF', 'TYSON FOODS');
insert into stocks( stock_symbol, stock_name) values ('VCJR', 'FII VECTIS');
insert into stocks( stock_symbol, stock_name) values ('VSEC', 'FII VOT SEC');
insert into stocks( stock_symbol, stock_name) values ('EQIA', 'FIAGRO EQIA');
insert into stocks( stock_symbol, stock_name) values ('HCRI', 'FII CRIANCA');
insert into stocks( stock_symbol, stock_name) values ('JFEN', 'JOAO FORTES');
insert into stocks( stock_symbol, stock_name) values ('HBRE', 'HBR REALTY');
insert into stocks( stock_symbol, stock_name) values ('GOAU', 'GERDAU MET');
insert into stocks( stock_symbol, stock_name) values ('LFTT', 'FII LOFT II');
insert into stocks( stock_symbol, stock_name) values ('EAIN', 'ELECTR ARTS');
insert into stocks( stock_symbol, stock_name) values ('RAPT', 'RANDON PART');
insert into stocks( stock_symbol, stock_name) values ('ENMT', 'ENERGISA MT');
insert into stocks( stock_symbol, stock_name) values ('PLPL', 'PLANOEPLANO');
insert into stocks( stock_symbol, stock_name) values ('RRRP', 'R PETROLEUMON');
insert into stocks( stock_symbol, stock_name) values ('BOVA', 'ISHARES BOVACI');
insert into stocks( stock_symbol, stock_name) values ('FEXC', 'FII EXCELLENCI');
insert into stocks( stock_symbol, stock_name) values ('BTAL', 'FII BTG AGROCI');
insert into stocks( stock_symbol, stock_name) values ('BMLC', 'FII BMBRC LCCI');
insert into stocks( stock_symbol, stock_name) values ('BBSD', 'BB ETF SP DVCI');
insert into stocks( stock_symbol, stock_name) values ('FHER', 'FER HERINGERON');
insert into stocks( stock_symbol, stock_name) values ('BRAX', 'ISHARES BRAXCI');
insert into stocks( stock_symbol, stock_name) values ('DVFF', 'FII DEVA FOFCI');
insert into stocks( stock_symbol, stock_name) values ('GEPA', 'GER PARANAP PN');
insert into stocks( stock_symbol, stock_name) values ('GGRC', 'FII GGRCOVEPCI');
insert into stocks( stock_symbol, stock_name) values ('MGLG', 'FII MOGNO LGCI');
insert into stocks( stock_symbol, stock_name) values ('GMAT', 'GRUPO MATEUSON');
insert into stocks( stock_symbol, stock_name) values ('CARD', 'CSU CARDSYSTON');
insert into stocks( stock_symbol, stock_name) values ('ESGU', 'TREND ESG USCI');
insert into stocks( stock_symbol, stock_name) values ('CRFB', 'CARREFOUR BRON');
insert into stocks( stock_symbol, stock_name) values ('JRDM', 'FII SHOPJSULCI');
insert into stocks( stock_symbol, stock_name) values ('BLMR', 'FII BLUE FOFCI');
insert into stocks( stock_symbol, stock_name) values ('BLMC', 'FII BLUE CRICI');
insert into stocks( stock_symbol, stock_name) values ('BPML', 'FII BTG SHOPCI');
insert into stocks( stock_symbol, stock_name) values ('CJCT', 'FII CJCTOWERCI');
insert into stocks( stock_symbol, stock_name) values ('CPFE', 'CPFL ENERGIAON');
insert into stocks( stock_symbol, stock_name) values ('FLMA', 'FII S F LIMACI');
insert into stocks( stock_symbol, stock_name) values ('FPOR', 'FIP PORT SUDCI');
insert into stocks( stock_symbol, stock_name) values ('GCRI', 'FII GLPG CRICI');
insert into stocks( stock_symbol, stock_name) values ('ALSO', 'ALIANSCSONAEON');
insert into stocks( stock_symbol, stock_name) values ('BBSE', 'BBSEGURIDADEON');
insert into stocks( stock_symbol, stock_name) values ('MDNE', 'MOURA DUBEUXON');
insert into stocks( stock_symbol, stock_name) values ('BTEK', 'INVESTO BTEKCI');
insert into stocks( stock_symbol, stock_name) values ('CMDB', 'BTG COMMODITCI');
insert into stocks( stock_symbol, stock_name) values ('ECOO', 'ISHARES ECOOCI');
insert into stocks( stock_symbol, stock_name) values ('BRML', 'BR MALLS PARON');
insert into stocks( stock_symbol, stock_name) values ('JALL', 'JALLESMACHADON');
insert into stocks( stock_symbol, stock_name) values ('LLIS', 'LE LIS BLANCON');
insert into stocks( stock_symbol, stock_name) values ('BOVB', 'ETF BRA IBOVCI');
insert into stocks( stock_symbol, stock_name) values ('GENB', 'ETF BTG GENBCI');
insert into stocks( stock_symbol, stock_name) values ('AFHI', 'FII AFHI CRICI');
insert into stocks( stock_symbol, stock_name) values ('CPTS', 'FII CAPI SECCI');
insert into stocks( stock_symbol, stock_name) values ('MGCR', 'FII MOGNO HGCI');
insert into stocks( stock_symbol, stock_name) values ('CPFF', 'FII CAP REITCI');
insert into stocks( stock_symbol, stock_name) values ('IRBR', 'IRBBRASIL REON');
insert into stocks( stock_symbol, stock_name) values ('GAME', 'FII GUARD MUCI');
insert into stocks( stock_symbol, stock_name) values ('BRGE', 'ALFA CONSORCON');
insert into stocks( stock_symbol, stock_name) values ('IBOB', 'PACTUAL IBOVCI');
insert into stocks( stock_symbol, stock_name) values ('MEGA', 'OMEGAENERGIAON');
insert into stocks( stock_symbol, stock_name) values ('PMAM', 'PARANAPANEMAON');
insert into stocks( stock_symbol, stock_name) values ('MGEL', 'MANGELS INDLPN');
insert into stocks( stock_symbol, stock_name) values ('OFSA', 'OUROFINO S/AON');
insert into stocks( stock_symbol, stock_name) values ('ONCO', 'ONCOCLINICASON');
insert into stocks( stock_symbol, stock_name) values ('QAGR', 'FII QUASAR ACI');
insert into stocks( stock_symbol, stock_name) values ('RBRP', 'FII RBR PROPCI');
insert into stocks( stock_symbol, stock_name) values ('RVBI', 'FII VBI REITCI');
insert into stocks( stock_symbol, stock_name) values ('SHOW', 'TIME FOR FUNON');
insert into stocks( stock_symbol, stock_name) values ('USTK', 'INVESTO USTKCI');
insert into stocks( stock_symbol, stock_name) values ('AMAR', 'LOJAS MARISAON');
insert into stocks( stock_symbol, stock_name) values ('BMIN', 'MERC INVEST PN');
insert into stocks( stock_symbol, stock_name) values ('CXRI', 'FII CX RBRAVCI');
insert into stocks( stock_symbol, stock_name) values ('HTMX', 'FII HOTEL MXCI');
insert into stocks( stock_symbol, stock_name) values ('LPSB', 'LOPES BRASILON');
insert into stocks( stock_symbol, stock_name) values ('MTRE', 'MITRE REALTYON');
insert into stocks( stock_symbol, stock_name) values ('ORPD', 'FII OURO PRTCI');
insert into stocks( stock_symbol, stock_name) values ('PCAR', 'P.ACUCAR-CBDON');
insert into stocks( stock_symbol, stock_name) values ('PSSA', 'PORTO SEGUROON');
insert into stocks( stock_symbol, stock_name) values ('RBRF', 'FII RBRALPHACI');
insert into stocks( stock_symbol, stock_name) values ('RECT', 'FII REC RENDCI');
insert into stocks( stock_symbol, stock_name) values ('RSUL', 'RIOSULENSE  PN');
insert into stocks( stock_symbol, stock_name) values ('RZAK', 'FII RIZA AKNCI');
insert into stocks( stock_symbol, stock_name) values ('VIGT', 'FIP VINCI IECI');
insert into stocks( stock_symbol, stock_name) values ('FCFL', 'FII CAMPUSFLCI');
insert into stocks( stock_symbol, stock_name) values ('EQIR', 'FII EQI RECECI');
insert into stocks( stock_symbol, stock_name) values ('IBFF', 'FII FOF BREICI');
insert into stocks( stock_symbol, stock_name) values ('CARE', 'FII DEA CARECI');
insert into stocks( stock_symbol, stock_name) values ('EURP', 'TREND EUROPACI');
insert into stocks( stock_symbol, stock_name) values ('ALMI', 'FII TORRE ALCI');
insert into stocks( stock_symbol, stock_name) values ('BDIV', 'FIP BTGDV IECI');
insert into stocks( stock_symbol, stock_name) values ('FATN', 'FII ATHENA ICI');
insert into stocks( stock_symbol, stock_name) values ('MDIA', 'M.DIASBRANCOON');
insert into stocks( stock_symbol, stock_name) values ('HOOT', 'HOTEIS OTHONPN');
insert into stocks( stock_symbol, stock_name) values ('LAME', 'LOJAS AMERICON');
insert into stocks( stock_symbol, stock_name) values ('GCFF', 'FII GALAPAGOCI');
insert into stocks( stock_symbol, stock_name) values ('AFOF', 'FII ALIANZFFCI');
insert into stocks( stock_symbol, stock_name) values ('FIVN', 'FII VIDANOVACI');
insert into stocks( stock_symbol, stock_name) values ('TASA', 'TAURUS ARMASON');
insert into stocks( stock_symbol, stock_name) values ('LAND', 'TERRASANTAPAON');
insert into stocks( stock_symbol, stock_name) values ('RBRR', 'FII RBRHGRADCI');
insert into stocks( stock_symbol, stock_name) values ('SNFF', 'FII SUNOFOFICI');
insert into stocks( stock_symbol, stock_name) values ('TEQI', 'FIA EQI TECHCI');
insert into stocks( stock_symbol, stock_name) values ('CTXT', 'FII C TEXTILCI');
insert into stocks( stock_symbol, stock_name) values ('ALUG', 'INVESTO ALUGCI');
insert into stocks( stock_symbol, stock_name) values ('CXSE', 'CAIXA SEGURION');
insert into stocks( stock_symbol, stock_name) values ('RBLG', 'FII RBCAP LGCI');
insert into stocks( stock_symbol, stock_name) values ('RBRY', 'FII RBR PCRICI');
insert into stocks( stock_symbol, stock_name) values ('VGIP', 'FII VALORAIPCI');
insert into stocks( stock_symbol, stock_name) values ('XTED', 'FII TRXE CORCI');
insert into stocks( stock_symbol, stock_name) values ('BZLI', 'FII BRREALTYCI');
insert into stocks( stock_symbol, stock_name) values ('OUFF', 'FII OURI FOFCI');
insert into stocks( stock_symbol, stock_name) values ('RECR', 'FII REC RECECI');
insert into stocks( stock_symbol, stock_name) values ('RPMG', 'PET MANGUINHON');
insert into stocks( stock_symbol, stock_name) values ('TPIS', 'TRIUNFO PARTON');
insert into stocks( stock_symbol, stock_name) values ('PLAS', 'PLASCAR PARTON');
insert into stocks( stock_symbol, stock_name) values ('JOGO', 'INVESTO JOGOCI');
insert into stocks( stock_symbol, stock_name) values ('CSAB', 'SEG AL BAHIAPN');
insert into stocks( stock_symbol, stock_name) values ('FSRF', 'FISET FL REFCI');
insert into stocks( stock_symbol, stock_name) values ('OURE', 'FII OU RENDACI');
insert into stocks( stock_symbol, stock_name) values ('RBIR', 'FII RBRES IVCI');
insert into stocks( stock_symbol, stock_name) values ('REDE', 'REDE ENERGIAON');
insert into stocks( stock_symbol, stock_name) values ('SMAB', 'BTG SMLL CAPCI');
insert into stocks( stock_symbol, stock_name) values ('SNCI', 'FII SUNO CRICI');
insert into stocks( stock_symbol, stock_name) values ('SYNE', 'SYN PROP TECON');
insert into stocks( stock_symbol, stock_name) values ('TRIG', 'TRG SMIC CAPCI');
insert into stocks( stock_symbol, stock_name) values ('WLMM', 'WLM IND COM PN');
insert into stocks( stock_symbol, stock_name) values ('FLCR', 'FII FL RECEBCI');
insert into stocks( stock_symbol, stock_name) values ('LOGG', 'LOG COM PROPON');
insert into stocks( stock_symbol, stock_name) values ('MORC', 'FII MORE CRICI');
insert into stocks( stock_symbol, stock_name) values ('BITH', 'BITCOIN HASHCI');
insert into stocks( stock_symbol, stock_name) values ('MGHT', 'FII MOGNO HTCI');
insert into stocks( stock_symbol, stock_name) values ('BMEB', 'MERC BRASIL PN');
insert into stocks( stock_symbol, stock_name) values ('CORM', 'FII CORE METCI');
insert into stocks( stock_symbol, stock_name) values ('POSI', 'POSITIVO TECON');
insert into stocks( stock_symbol, stock_name) values ('PRSV', 'FII P VARGASCI');
insert into stocks( stock_symbol, stock_name) values ('TORD', 'FII TORDE EICI');
insert into stocks( stock_symbol, stock_name) values ('XBOV', 'CAIXAETFXBOVCI');
insert into stocks( stock_symbol, stock_name) values ('BLMG', 'FII BLUE LOGCI');
insert into stocks( stock_symbol, stock_name) values ('CYRE', 'CYRELA REALTON');
insert into stocks( stock_symbol, stock_name) values ('BOVS', 'SAFRAETFIBOVCI');
insert into stocks( stock_symbol, stock_name) values ('RADL', 'RAIADROGASILON');
insert into stocks( stock_symbol, stock_name) values ('SANB', 'SANTANDER BRON');
insert into stocks( stock_symbol, stock_name) values ('SMAL', 'ISHARES SMALCI');
insert into stocks( stock_symbol, stock_name) values ('VGIR', 'FII VALREIIICI');
insert into stocks( stock_symbol, stock_name) values ('VSLH', 'FII VERS CRICI');
insert into stocks( stock_symbol, stock_name) values ('WRLD', 'INVESTO WRLDCI');
insert into stocks( stock_symbol, stock_name) values ('XFIX', 'TREND IFIX-LCI');
insert into stocks( stock_symbol, stock_name) values ('XPML', 'FII XP MALLSCI');
insert into stocks( stock_symbol, stock_name) values ('KEPL', 'KEPLER WEBERON');
insert into stocks( stock_symbol, stock_name) values ('BRIV', 'ALFA INVEST PN');
insert into stocks( stock_symbol, stock_name) values ('SMTO', 'SAO MARTINHOON');
insert into stocks( stock_symbol, stock_name) values ('HGLG', 'FII CSHG LOGCI');
insert into stocks( stock_symbol, stock_name) values ('BAAX', 'MSCI ASIA JPDRN');
insert into stocks( stock_symbol, stock_name) values ('BSLV', 'SILVER TRUSTDRN');
insert into stocks( stock_symbol, stock_name) values ('BIJR', 'CORESMALLCAPDRN');
insert into stocks( stock_symbol, stock_name) values ('BTRA', 'FII BTG TAGRCI');
insert into stocks( stock_symbol, stock_name) values ('AVGO', 'BROADCOM INCDRN');
insert into stocks( stock_symbol, stock_name) values ('BIXJ', 'GLOBALHEALTHDRN');
insert into stocks( stock_symbol, stock_name) values ('BBPO', 'FII BB PRGIICI');
insert into stocks( stock_symbol, stock_name) values ('BXTC', 'EXPON TECHNLDRN');
insert into stocks( stock_symbol, stock_name) values ('BHEF', 'CURHEDGEMSCIDRN');
insert into stocks( stock_symbol, stock_name) values ('BEWL', 'MSCI SWITZERDRN');
insert into stocks( stock_symbol, stock_name) values ('AXPB', 'AMERICAN EXPDRN');
insert into stocks( stock_symbol, stock_name) values ('CXCO', 'FII CEF CORPCI');
insert into stocks( stock_symbol, stock_name) values ('BIEF', 'COREMSCIEAFEDRN');
insert into stocks( stock_symbol, stock_name) values ('FLTC', 'FLEETCOR TECDRN');
insert into stocks( stock_symbol, stock_name) values ('BSOX', 'BKR SEMICONDDRN');
insert into stocks( stock_symbol, stock_name) values ('MFAI', 'FII MERITOFACI');
insert into stocks( stock_symbol, stock_name) values ('BAER', 'US AEROSPACEDRN');
insert into stocks( stock_symbol, stock_name) values ('MDLZ', 'MONDELEZ INTDRN');
insert into stocks( stock_symbol, stock_name) values ('MFII', 'FII MERITO ICI');
insert into stocks( stock_symbol, stock_name) values ('BFDL', 'FTMOR DV LEADRN');
insert into stocks( stock_symbol, stock_name) values ('KNHY', 'FII KINEA HYCI');
insert into stocks( stock_symbol, stock_name) values ('LSXM', 'LIBERTY MEDIDRN');
insert into stocks( stock_symbol, stock_name) values ('BOAC', 'BANK AMERICADRN');
insert into stocks( stock_symbol, stock_name) values ('HPDP', 'FII HEDGEPDPCI');
insert into stocks( stock_symbol, stock_name) values ('BCRI', 'FII BEES CRICI');
insert into stocks( stock_symbol, stock_name) values ('BUSR', 'CORE US REITDRN');
insert into stocks( stock_symbol, stock_name) values ('BIHI', 'USMEDICDEVICDRN');
insert into stocks( stock_symbol, stock_name) values ('HCHG', 'FII HECT CRICI');
insert into stocks( stock_symbol, stock_name) values ('FPAB', 'FII A BRANCACI');
insert into stocks( stock_symbol, stock_name) values ('HGPO', 'FII CSHGPRIMCI');
insert into stocks( stock_symbol, stock_name) values ('KMIC', 'KINDER MORGADRN');
insert into stocks( stock_symbol, stock_name) values ('BEFV', 'MSCIEAFEVALUDRN');
insert into stocks( stock_symbol, stock_name) values ('BPFF', 'FII ABSOLUTOCI');
insert into stocks( stock_symbol, stock_name) values ('ABCP', 'FII ABC IMOBCI');
insert into stocks( stock_symbol, stock_name) values ('BIYW', 'US TECHNOLOGDRN');
insert into stocks( stock_symbol, stock_name) values ('BDVY', 'SELECT DIVIDDRN');
insert into stocks( stock_symbol, stock_name) values ('BSUS', 'ESGMSCIUSA LDRN');
insert into stocks( stock_symbol, stock_name) values ('DGCO', 'DOLLAR GENERDRN');
insert into stocks( stock_symbol, stock_name) values ('BEWY', 'MSCISOUTHKORDRN');
insert into stocks( stock_symbol, stock_name) values ('BGWH', 'COREDIVGROWTDRN');
insert into stocks( stock_symbol, stock_name) values ('KNSC', 'FII KINEA SCCI');
insert into stocks( stock_symbol, stock_name) values ('GDBR', 'GEN DYNAMICSDRN');
insert into stocks( stock_symbol, stock_name) values ('BEZU', 'MSCIEUROZONEDRN');
insert into stocks( stock_symbol, stock_name) values ('BIGF', 'GLOBAL INFRADRN');
insert into stocks( stock_symbol, stock_name) values ('BEGU', 'TRUSTMSCI USDRN');
insert into stocks( stock_symbol, stock_name) values ('HSML', 'FII HSI MALLCI');
insert into stocks( stock_symbol, stock_name) values ('KNCR', 'FII KINEA RICI');
insert into stocks( stock_symbol, stock_name) values ('BIYG', 'USFINANCSERVDRN');
insert into stocks( stock_symbol, stock_name) values ('HREC', 'FII HEDGERECCI');
insert into stocks( stock_symbol, stock_name) values ('IDFI', 'FII UNIDADESCI');
insert into stocks( stock_symbol, stock_name) values ('LREN', 'LOJAS RENNERON');
insert into stocks( stock_symbol, stock_name) values ('CBOP', 'FII C BRANCOCI');
insert into stocks( stock_symbol, stock_name) values ('NOCG', 'NORTHROP GRUDRN');
insert into stocks( stock_symbol, stock_name) values ('RBHY', 'FII RB YIELDCI');
insert into stocks( stock_symbol, stock_name) values ('RMAI', 'FII REAGMULTCI');
insert into stocks( stock_symbol, stock_name) values ('RNDP', 'FII BB R PAPCI');
insert into stocks( stock_symbol, stock_name) values ('SLBG', 'SCHLUMBERGERDRN');
insert into stocks( stock_symbol, stock_name) values ('TJXC', 'TJX COMPANIEDRN');
insert into stocks( stock_symbol, stock_name) values ('TRXB', 'FII TRX R IICI');
insert into stocks( stock_symbol, stock_name) values ('VOTS', 'FII V MASTERCI');
insert into stocks( stock_symbol, stock_name) values ('XPCA', 'FIAGRO XP CACI');
insert into stocks( stock_symbol, stock_name) values ('ELCI', 'ESTEE LAUDERDRN');
insert into stocks( stock_symbol, stock_name) values ('CPRL', 'CANAD PACIFIDRN');
insert into stocks( stock_symbol, stock_name) values ('BMYB', 'BRISTOLMYERSDRN');
insert into stocks( stock_symbol, stock_name) values ('KINP', 'FII EV KINEACI');
insert into stocks( stock_symbol, stock_name) values ('JSAF', 'FII JS A FINCI');
insert into stocks( stock_symbol, stock_name) values ('BEWA', 'MSCIAUSTRALIDRN');
insert into stocks( stock_symbol, stock_name) values ('GTWR', 'FII G TOWERSCI');
insert into stocks( stock_symbol, stock_name) values ('BEGE', 'INC ESG AWARDRN');
insert into stocks( stock_symbol, stock_name) values ('BIEM', 'COREMSCI EMKDRN');
insert into stocks( stock_symbol, stock_name) values ('BITO', 'CORE SP TOTADRN');
insert into stocks( stock_symbol, stock_name) values ('KNIP', 'FII KINEA IPCI');
insert into stocks( stock_symbol, stock_name) values ('MUTC', 'MICRON TECHNDRN');
insert into stocks( stock_symbol, stock_name) values ('PLCR', 'FII PLURAL RCI');
insert into stocks( stock_symbol, stock_name) values ('PLOG', 'FII PLURAL LCI');
insert into stocks( stock_symbol, stock_name) values ('PORD', 'FII POLO CRICI');
insert into stocks( stock_symbol, stock_name) values ('RBHG', 'FII RBCRI IVCI');
insert into stocks( stock_symbol, stock_name) values ('RPAD', 'ALFA HOLDINGPNB');
insert into stocks( stock_symbol, stock_name) values ('RRCI', 'FII RBCAP RICI');
insert into stocks( stock_symbol, stock_name) values ('SHPH', 'FII HIGIENOPCI');
insert into stocks( stock_symbol, stock_name) values ('SLCE', 'SLC AGRICOLAON');
insert into stocks( stock_symbol, stock_name) values ('STZB', 'CONSTELLATIODRN');
insert into stocks( stock_symbol, stock_name) values ('XPCM', 'FII XP MACAECI');
insert into stocks( stock_symbol, stock_name) values ('MOOO', 'ALTRIA GROUPDRN');
insert into stocks( stock_symbol, stock_name) values ('DHER', 'DANAHER CORPDRN');
insert into stocks( stock_symbol, stock_name) values ('FIGS', 'FII GEN SHOPCI');
insert into stocks( stock_symbol, stock_name) values ('BUSM', 'MSCI US MVOLDRN');
insert into stocks( stock_symbol, stock_name) values ('HGRU', 'FII CSHG URBCI');
insert into stocks( stock_symbol, stock_name) values ('IGTI', 'IGUATEMI S.AON');
insert into stocks( stock_symbol, stock_name) values ('TRPL', 'TRAN PAULISTON');
insert into stocks( stock_symbol, stock_name) values ('BRBI', 'BR PARTNERS UNT');
insert into stocks( stock_symbol, stock_name) values ('GSGI', 'GOLDMANSACHSDRN');
insert into stocks( stock_symbol, stock_name) values ('MXRF', 'FII MAXI RENCI');
insert into stocks( stock_symbol, stock_name) values ('PQAG', 'FII PARQ ANHCI');
insert into stocks( stock_symbol, stock_name) values ('REGN', 'REGENERON PHDRN');
insert into stocks( stock_symbol, stock_name) values ('RYTT', 'RAYTHEONTECHDRN');
insert into stocks( stock_symbol, stock_name) values ('VCRR', 'FII VECT RENCI');
insert into stocks( stock_symbol, stock_name) values ('VIFI', 'FII VINCI IFCI');
insert into stocks( stock_symbol, stock_name) values ('VISC', 'FII VINCI SCCI');
insert into stocks( stock_symbol, stock_name) values ('XPSF', 'FII XP SELECCI');
insert into stocks( stock_symbol, stock_name) values ('BIEU', 'COREMSCI EURDRN');
insert into stocks( stock_symbol, stock_name) values ('JPPA', 'FII JPPMOGNOCI');
insert into stocks( stock_symbol, stock_name) values ('KFOF', 'FII KINEAFOFCI');
insert into stocks( stock_symbol, stock_name) values ('HBRH', 'FII MULT RENCI');
insert into stocks( stock_symbol, stock_name) values ('LGCP', 'FII LGCP INTCI');
insert into stocks( stock_symbol, stock_name) values ('BEWH', 'MSCIHONGKONGDRN');
insert into stocks( stock_symbol, stock_name) values ('NEXT', 'NEXTERA ENERDRN');
insert into stocks( stock_symbol, stock_name) values ('RDPD', 'FII BB PAPIICI');
insert into stocks( stock_symbol, stock_name) values ('REIT', 'FII REIT RIVCI');
insert into stocks( stock_symbol, stock_name) values ('TRXF', 'FII TRX REALCI');
insert into stocks( stock_symbol, stock_name) values ('VINO', 'FII VINCI OFCI');
insert into stocks( stock_symbol, stock_name) values ('CMIN', 'CSNMINERACAOON');
insert into stocks( stock_symbol, stock_name) values ('HGFF', 'FII CSHG FOFCI');
insert into stocks( stock_symbol, stock_name) values ('HSRE', 'FII HSIRENDACI');
insert into stocks( stock_symbol, stock_name) values ('BEEM', 'MSCI EMGMARKDRN');
insert into stocks( stock_symbol, stock_name) values ('FVPQ', 'FII V PARQUECI');
insert into stocks( stock_symbol, stock_name) values ('HABT', 'FII HABIT IICI');
insert into stocks( stock_symbol, stock_name) values ('VGHF', 'FII VALOR HECI');
insert into stocks( stock_symbol, stock_name) values ('VILG', 'FII VINCI LGCI');
insert into stocks( stock_symbol, stock_name) values ('BVLU', 'MSCIUSvaluesFDRN');
insert into stocks( stock_symbol, stock_name) values ('AALL', 'AMERICAN AIRDRN');
insert into stocks( stock_symbol, stock_name) values ('GALG', 'FII GUARDIANCI');
insert into stocks( stock_symbol, stock_name) values ('HLOG', 'FII HEDGELOGCI');
insert into stocks( stock_symbol, stock_name) values ('SARE', 'FII SANT RENCI');
insert into stocks( stock_symbol, stock_name) values ('TPRY', 'TAPESTRY INCDRN');
insert into stocks( stock_symbol, stock_name) values ('UNHH', 'UNITEDHEALTHDRN');
insert into stocks( stock_symbol, stock_name) values ('VRTA', 'FII FATOR VECI');
insert into stocks( stock_symbol, stock_name) values ('CHCM', 'CHARTER COMMDRN');
insert into stocks( stock_symbol, stock_name) values ('OXYP', 'OCCIDENT PTRDRN');
insert into stocks( stock_symbol, stock_name) values ('PATL', 'FII PATR LOGCI');
insert into stocks( stock_symbol, stock_name) values ('PEMA', 'FII PERFORMACI');
insert into stocks( stock_symbol, stock_name) values ('QAMI', 'FII QUASAR CCI');
insert into stocks( stock_symbol, stock_name) values ('RBCO', 'FII R INCOMECI');
insert into stocks( stock_symbol, stock_name) values ('RNGO', 'FII RIONEGROCI');
insert into stocks( stock_symbol, stock_name) values ('SADI', 'FII SANT PAPCI');
insert into stocks( stock_symbol, stock_name) values ('THGI', 'HANOVER INSUDRN');
insert into stocks( stock_symbol, stock_name) values ('TMOS', 'THERMFISCHERDRN');
insert into stocks( stock_symbol, stock_name) values ('UPAC', 'UNIONPACIFICDRN');
insert into stocks( stock_symbol, stock_name) values ('WUNI', 'WESTERNUNIONDRN');
insert into stocks( stock_symbol, stock_name) values ('BQUA', 'MSCIUSQUAL FDRN');
insert into stocks( stock_symbol, stock_name) values ('BNFS', 'FII BANRISULCI');
insert into stocks( stock_symbol, stock_name) values ('BEGD', 'TRTMSCI');
insert into stocks( stock_symbol, stock_name) values ('TFCO', 'TRACK FIELD PN');
insert into stocks( stock_symbol, stock_name) values ('LBRD', 'LIBERTY BROADRN');
insert into stocks( stock_symbol, stock_name) values ('BEWG', 'MSCI GERMANYDRN');
insert into stocks( stock_symbol, stock_name) values ('MALL', 'FII MALLS BPCI');
insert into stocks( stock_symbol, stock_name) values ('BEFG', 'MSCIEAFEGROWDRN');
insert into stocks( stock_symbol, stock_name) values ('AIEC', 'FII AUTONOMYCI');
insert into stocks( stock_symbol, stock_name) values ('ABCB', 'ABC BRASIL  PN');
insert into stocks( stock_symbol, stock_name) values ('PHMO', 'PHILIP MORRIDRN');
insert into stocks( stock_symbol, stock_name) values ('VIUR', 'FII VINCI IUCI');
insert into stocks( stock_symbol, stock_name) values ('VSHO', 'FII VOT SHOPCI');
insert into stocks( stock_symbol, stock_name) values ('CRDA', 'CREDIT ACCEPDRN');
insert into stocks( stock_symbol, stock_name) values ('MELI', 'MERCADOLIBREDRN');
insert into stocks( stock_symbol, stock_name) values ('CACR', 'CARTESIA FIICI');
insert into stocks( stock_symbol, stock_name) values ('EGIE', 'ENGIE BRASILON');
insert into stocks( stock_symbol, stock_name) values ('AZOI', 'AUTOZONE INCDRN');
insert into stocks( stock_symbol, stock_name) values ('BMTU', 'MSCIUSAMOM FDRN');
insert into stocks( stock_symbol, stock_name) values ('ADPR', 'AUTOMATIC DTDRN');
insert into stocks( stock_symbol, stock_name) values ('BIYF', 'US FINANCIALDRN');
insert into stocks( stock_symbol, stock_name) values ('HAAA', 'FII HEDGEAAACI');
insert into stocks( stock_symbol, stock_name) values ('MYPK', 'IOCHP-MAXIONON');
insert into stocks( stock_symbol, stock_name) values ('OUJP', 'FII OURI JPPCI');
insert into stocks( stock_symbol, stock_name) values ('SPTW', 'FII SP DOWNTCI');
insert into stocks( stock_symbol, stock_name) values ('TEPP', 'FII TEL PROPCI');
insert into stocks( stock_symbol, stock_name) values ('TGAR', 'FII TG ATIVOCI');
insert into stocks( stock_symbol, stock_name) values ('URPR', 'FII URCA RENCI');
insert into stocks( stock_symbol, stock_name) values ('VIVT', 'TELEF BRASILON');
insert into stocks( stock_symbol, stock_name) values ('VRSN', 'VERISIGN INCDRN');
insert into stocks( stock_symbol, stock_name) values ('VRTX', 'VERTEX PHARMDRN');
insert into stocks( stock_symbol, stock_name) values ('HGCR', 'FII CSHG CRICI');
insert into stocks( stock_symbol, stock_name) values ('BFXI', 'CHINALARGECADRN');
insert into stocks( stock_symbol, stock_name) values ('HUSC', 'FII H UNIMEDCI');
insert into stocks( stock_symbol, stock_name) values ('KNRE', 'FII KII REALCI');
insert into stocks( stock_symbol, stock_name) values ('ITUB', 'ITAUUNIBANCOON');
insert into stocks( stock_symbol, stock_name) values ('BICL', 'BKR GL CLEANDRN');
insert into stocks( stock_symbol, stock_name) values ('BDIF', 'FIC INFR BTGFIDC');
insert into stocks( stock_symbol, stock_name) values ('JURO', 'SPARTA INFRAFIDC');
insert into stocks( stock_symbol, stock_name) values ('DCVY', 'DISCOVERY INDRN A');
insert into stocks( stock_symbol, stock_name) values ('IFRA', 'FI ITAUINFRAFIDCER');
insert into stocks( stock_symbol, stock_name) values ('KDIF', 'KINEA INFRAFFIDCER');
insert into stocks( stock_symbol, stock_name) values ('PICE', 'FIP PATR INFCI');
insert into stocks( stock_symbol, stock_name) values ('XPIE', 'FIP XP INFRACI');
insert into stocks( stock_symbol, stock_name) values ('ENDD', 'FIP END DEBTCI');
insert into stocks( stock_symbol, stock_name) values ('CPTI', 'FIC IE CAP  FIDCER');
insert into stocks( stock_symbol, stock_name) values ('XPID', 'FIRF XP IE  FIDCEA');
insert into stocks( stock_symbol, stock_name) values ('SLED', 'SARAIVA LIVRON');